# Generated by Django 3.2.16 on 2023-01-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='image',
            field=models.ImageField(default='exit', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
